[package]
name = "potd-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.89"
clap = { version = "4.5.40", features = ["derive"] }
regex = "1.11.1"
reqwest = "0.12.20"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
